import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1747244225044 implements MigrationInterface {
    name = 'InitSchema1747244225044'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "character_properties" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "group" character varying(20) NOT NULL, "key" character varying(50) NOT NULL, "value" jsonb NOT NULL, "value_type" character varying(10) NOT NULL, "order" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "character_id" uuid, CONSTRAINT "PK_1e30ec5ab540ee0048b8200fc8c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_prop_char_key" ON "character_properties" ("character_id", "key") `);
        await queryRunner.query(`CREATE TABLE "characters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(60) NOT NULL, "slug" character varying(80) NOT NULL, "avatar_url" text, "bio" text, "backstory" text, "attributes" jsonb NOT NULL DEFAULT '{}', "visibility" boolean NOT NULL DEFAULT true, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "UQ_df9b751251a0aee20739af7d4f5" UNIQUE ("slug"), CONSTRAINT "PK_9d731e05758f26b9315dac5e378" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_char_slug" ON "characters" ("slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_char_user_name" ON "characters" ("user_id", "name") `);
        await queryRunner.query(`CREATE TABLE "guild_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(40) NOT NULL, "color" character varying(7) NOT NULL, "icon" character varying(50), "position" integer NOT NULL, "permissions" integer NOT NULL DEFAULT '0', "is_leader" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "guild_id" uuid, CONSTRAINT "CHK_d765f955f222f22c22257b8920" CHECK ("position" >= 0), CONSTRAINT "PK_615022972f3f407b398a7125283" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_role_one_leader" ON "guild_roles" ("guild_id") WHERE "is_leader" = TRUE`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_role_position" ON "guild_roles" ("guild_id", "position") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_role_name" ON "guild_roles" ("guild_id", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."guild_memberships_status_enum" AS ENUM('pending', 'active', 'kicked', 'left')`);
        await queryRunner.query(`CREATE TABLE "guild_memberships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."guild_memberships_status_enum" NOT NULL, "joined_at" TIMESTAMP WITH TIME ZONE, "left_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid, "guild_id" uuid, "role_id" uuid, "invited_by_id" uuid, CONSTRAINT "CHK_8a4f8bb644d2b3802879db16c7" CHECK ("joined_at" IS NOT NULL OR status = 'pending'), CONSTRAINT "PK_a73845279be917eb423fe92a56a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_gm_guild_active" ON "guild_memberships" ("guild_id") WHERE "status" = 'active'`);
        await queryRunner.query(`CREATE INDEX "ix_gm_status" ON "guild_memberships" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_gm_user_guild" ON "guild_memberships" ("user_id", "guild_id") `);
        await queryRunner.query(`CREATE TABLE "guild_poll_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "option_text" character varying(120) NOT NULL, "position" integer NOT NULL, "votes_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "announcement_id" uuid, CONSTRAINT "PK_00421febd0b9be495fdf177d276" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_gpo_announcement" ON "guild_poll_options" ("announcement_id", "position") `);
        await queryRunner.query(`CREATE TYPE "public"."guild_announcements_type_enum" AS ENUM('general', 'poll')`);
        await queryRunner.query(`CREATE TABLE "guild_announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(120) NOT NULL, "content" text NOT NULL, "type" "public"."guild_announcements_type_enum" NOT NULL, "close_at" TIMESTAMP WITH TIME ZONE, "show_results" boolean NOT NULL DEFAULT true, "multi_select" boolean NOT NULL DEFAULT false, "max_choices" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "guild_id" uuid, "author_user_id" uuid, "author_character_id" uuid, CONSTRAINT "CHK_ebf043477824698815b2446575" CHECK ((
    (type = 'poll'    AND close_at IS NOT NULL) OR
    (type = 'general' AND close_at IS NULL)
  )), CONSTRAINT "PK_6f287cf2cf71df974ad544b6560" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_ga_type" ON "guild_announcements" ("type") `);
        await queryRunner.query(`CREATE INDEX "ix_ga_guild_created" ON "guild_announcements" ("guild_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."guild_event_attendance_status_enum" AS ENUM('confirmed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "guild_event_attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."guild_event_attendance_status_enum" NOT NULL DEFAULT 'confirmed', "changed_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "event_id" uuid, "user_id" uuid, "character_id" uuid, CONSTRAINT "PK_3eca8a6d87903db74fef2384b88" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_gatt_event_confirmed" ON "guild_event_attendance" ("event_id") WHERE "status" = 'confirmed'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_gatt_user_event" ON "guild_event_attendance" ("event_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."guild_internal_events_status_enum" AS ENUM('scheduled', 'cancelled', 'completed')`);
        await queryRunner.query(`CREATE TABLE "guild_internal_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(120) NOT NULL, "description" text, "banner_url" text, "location_text" character varying(120), "latitude" numeric(9,6), "longitude" numeric(9,6), "start_at" TIMESTAMP WITH TIME ZONE NOT NULL, "end_at" TIMESTAMP WITH TIME ZONE, "capacity" integer, "attendee_count" integer NOT NULL DEFAULT '0', "status" "public"."guild_internal_events_status_enum" NOT NULL DEFAULT 'scheduled', "highlighted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "guild_id" uuid, "creator_user_id" uuid, "creator_character_id" uuid, CONSTRAINT "CHK_dc5442bff57b4b4c9107311558" CHECK ("end_at" IS NULL OR "end_at" > "start_at"), CONSTRAINT "PK_dfb82bb315643632a7a99703e85" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_gie_status" ON "guild_internal_events" ("status") `);
        await queryRunner.query(`CREATE INDEX "ix_gie_guild_start" ON "guild_internal_events" ("guild_id", "start_at") `);
        await queryRunner.query(`CREATE TYPE "public"."guilds_privacy_enum" AS ENUM('public', 'private')`);
        await queryRunner.query(`CREATE TYPE "public"."guilds_access_type_enum" AS ENUM('public', 'invite', 'code')`);
        await queryRunner.query(`CREATE TABLE "guilds" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(60) NOT NULL, "slug" character varying(80) NOT NULL, "description" text, "emblem_url" text, "rules" text, "history" text, "privacy" "public"."guilds_privacy_enum" NOT NULL DEFAULT 'public', "access_type" "public"."guilds_access_type_enum" NOT NULL DEFAULT 'public', "access_code_hash" character varying(255), "member_count" integer NOT NULL DEFAULT '1', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "leader_user_id" uuid NOT NULL, CONSTRAINT "UQ_6a78fec8e0d3b1e58794581def2" UNIQUE ("slug"), CONSTRAINT "CHK_df6b0ee12e5873d18dfd1287ed" CHECK ("member_count" >= 1), CONSTRAINT "PK_e7e7f2a51bd6d96a9ac2aa560f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_guild_leader" ON "guilds" ("leader_user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_guild_slug" ON "guilds" ("slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_guild_name" ON "guilds" ("name") `);
        await queryRunner.query(`CREATE TABLE "event_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(40) NOT NULL, "slug" character varying(60) NOT NULL, "color" character varying(7) NOT NULL, "description" text, "position" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_0e841f449e58e7dde739ba587f2" UNIQUE ("slug"), CONSTRAINT "PK_a6368447a61afbf9def09fd81af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_ec_pos" ON "event_categories" ("position") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_ec_slug" ON "event_categories" ("slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_ec_name" ON "event_categories" ("name") `);
        await queryRunner.query(`CREATE TABLE "event_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file_url" text NOT NULL, "thumbnail_url" text, "file_name" character varying(140) NOT NULL, "content_type" character varying(100) NOT NULL, "size_bytes" bigint NOT NULL, "width_px" integer, "height_px" integer, "caption" character varying(200), "position" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "event_id" uuid, "uploader_user_id" uuid, CONSTRAINT "PK_4e5f0c8c1718c8c2026c15296af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_em_mime" ON "event_media" ("content_type") `);
        await queryRunner.query(`CREATE INDEX "ix_em_event_pos" ON "event_media" ("event_id", "position") `);
        await queryRunner.query(`CREATE TYPE "public"."global_events_status_enum" AS ENUM('scheduled', 'cancelled', 'completed')`);
        await queryRunner.query(`CREATE TABLE "global_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(120) NOT NULL, "slug" character varying(140) NOT NULL, "description" text NOT NULL, "banner_url" text, "location_text" character varying(120) NOT NULL, "latitude" numeric(9,6), "longitude" numeric(9,6), "start_at" TIMESTAMP WITH TIME ZONE NOT NULL, "end_at" TIMESTAMP WITH TIME ZONE, "capacity" integer, "attendee_count" integer NOT NULL DEFAULT '0', "status" "public"."global_events_status_enum" NOT NULL DEFAULT 'scheduled', "featured" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "creator_user_id" uuid, "category_id" uuid, CONSTRAINT "UQ_1cbea2d00953335d61df5bb4e81" UNIQUE ("slug"), CONSTRAINT "CHK_d20aab1a32d67b7a6ad40ce12a" CHECK ((capacity IS NULL OR capacity > 0)), CONSTRAINT "CHK_f9602149c0dda740716d292f92" CHECK (((latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL))), CONSTRAINT "CHK_06f7e40ae07ad5285fba9fae13" CHECK ((end_at IS NULL OR end_at > start_at)), CONSTRAINT "PK_8bcd6a848c693643e3887b529f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_ge_status_date" ON "global_events" ("status", "start_at") `);
        await queryRunner.query(`CREATE INDEX "ix_ge_cat_start" ON "global_events" ("category_id", "start_at") `);
        await queryRunner.query(`CREATE TYPE "public"."global_event_attendance_status_enum" AS ENUM('confirmed', 'cancelled', 'waitlisted')`);
        await queryRunner.query(`CREATE TABLE "global_event_attendance" ("event_id" uuid NOT NULL, "user_id" uuid NOT NULL, "status" "public"."global_event_attendance_status_enum" NOT NULL DEFAULT 'confirmed', "changed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "character_id" uuid, CONSTRAINT "PK_8c9e8e6ceb7364d570b9cae5865" PRIMARY KEY ("event_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "ix_gea_user" ON "global_event_attendance" ("user_id", "changed_at") `);
        await queryRunner.query(`CREATE INDEX "ix_gea_event_status" ON "global_event_attendance" ("event_id") WHERE "status" = 'confirmed'`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "username" character varying(30) NOT NULL, "display_name" character varying(50), "avatar_url" text, "locale" character varying(10) NOT NULL DEFAULT 'es', "is_email_verified" boolean NOT NULL DEFAULT false, "is_admin" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "active_character_id" uuid, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_users_active_char" ON "users" ("active_character_id") WHERE "active_character_id" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_users_username" ON "users" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "guild_votes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "announcement_id" uuid, "poll_option_id" uuid, "user_id" uuid, "character_id" uuid, CONSTRAINT "PK_a60cb24c11f355d3d59ffdbb414" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_gv_one_vote_per_option" ON "guild_votes" ("poll_option_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."guild_invites_type_enum" AS ENUM('invite', 'request')`);
        await queryRunner.query(`CREATE TYPE "public"."guild_invites_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TABLE "guild_invites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."guild_invites_type_enum" NOT NULL, "email" character varying(255), "token_hash" character varying(255), "expires_at" TIMESTAMP WITH TIME ZONE, "status" "public"."guild_invites_status_enum" NOT NULL DEFAULT 'pending', "handled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "guild_id" uuid, "sender_user_id" uuid, "target_user_id" uuid, "handled_by_user_id" uuid, CONSTRAINT "PK_aedbe09a57f7cf8e248448db64b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_gi_token_hash" ON "guild_invites" ("token_hash") WHERE "token_hash" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "ix_gi_guild_status" ON "guild_invites" ("guild_id", "status") `);
        await queryRunner.query(`CREATE TABLE "chat_attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file_url" text NOT NULL, "file_name" character varying(140) NOT NULL, "content_type" character varying(100) NOT NULL, "size_bytes" bigint NOT NULL, "width_px" integer, "height_px" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "message_id" uuid, CONSTRAINT "PK_6752d3c3498926995b12c0a04bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_ca_mime" ON "chat_attachments" ("content_type") `);
        await queryRunner.query(`CREATE INDEX "ix_ca_message" ON "chat_attachments" ("message_id") `);
        await queryRunner.query(`CREATE TABLE "chat_message_reads" ("message_id" uuid NOT NULL, "user_id" uuid NOT NULL, "read_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_05c631ceddd3c425b5afc5b063c" PRIMARY KEY ("message_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "ix_cmr_message" ON "chat_message_reads" ("message_id") `);
        await queryRunner.query(`CREATE INDEX "ix_cmr_user" ON "chat_message_reads" ("user_id", "read_at") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_type_enum" AS ENUM('text', 'system', 'media')`);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."chat_messages_type_enum" NOT NULL, "content" text NOT NULL, "sent_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "edited_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "channel_id" uuid, "sender_user_id" uuid, "sender_character_id" uuid, "reply_to_id" uuid, CONSTRAINT "CHK_c382c9331aa2dbff923b231063" CHECK ((
    (type = 'system' AND sender_user_id IS NULL) OR
    (type <> 'system' AND sender_user_id IS NOT NULL)
  )), CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_cm_channel_sent" ON "chat_messages" ("channel_id", "sent_at") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_channels_type_enum" AS ENUM('direct', 'guild')`);
        await queryRunner.query(`CREATE TABLE "chat_channels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."chat_channels_type_enum" NOT NULL, "direct_hash" character varying(64), "topic" character varying(120), "last_message_at" TIMESTAMP WITH TIME ZONE, "is_archived" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "guild_id" uuid, CONSTRAINT "CHK_2807a736c7be5ae3fae5739272" CHECK ((
    (type = 'guild'  AND guild_id IS NOT NULL AND direct_hash IS NULL) OR
    (type = 'direct' AND guild_id IS NULL     AND direct_hash IS NOT NULL)
  )), CONSTRAINT "PK_efecd102855fb96e1428306ec6f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_cc_direct_hash" ON "chat_channels" ("direct_hash") WHERE "type" = 'direct'`);
        await queryRunner.query(`CREATE INDEX "ix_cc_lastmsg" ON "chat_channels" ("last_message_at") `);
        await queryRunner.query(`CREATE INDEX "ix_cc_guild" ON "chat_channels" ("guild_id") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_participants_role_enum" AS ENUM('member', 'moderator')`);
        await queryRunner.query(`CREATE TYPE "public"."chat_participants_status_enum" AS ENUM('active', 'left')`);
        await queryRunner.query(`CREATE TABLE "chat_participants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" "public"."chat_participants_role_enum" NOT NULL DEFAULT 'member', "status" "public"."chat_participants_status_enum" NOT NULL DEFAULT 'active', "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "left_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "channel_id" uuid, "user_id" uuid, "character_id" uuid, CONSTRAINT "CHK_8e29887d0bcb35214454954304" CHECK ((
    (status = 'active' AND left_at IS NULL) OR
    (status = 'left'   AND left_at IS NOT NULL)
  )), CONSTRAINT "PK_ebf68c52a2b4dceb777672b782d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_cp_channel_active" ON "chat_participants" ("channel_id") WHERE "status" = 'active'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_cp_user_channel" ON "chat_participants" ("channel_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token_hash" character varying(255) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used" boolean NOT NULL DEFAULT false, "used_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_prt_expires" ON "password_reset_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "ix_prt_user_id" ON "password_reset_tokens" ("user_id") WHERE "user_id" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ux_prt_token_hash" ON "password_reset_tokens" ("token_hash") `);
        await queryRunner.query(`ALTER TABLE "character_properties" ADD CONSTRAINT "FK_7558da41805c32a4570072842bd" FOREIGN KEY ("character_id") REFERENCES "characters"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "characters" ADD CONSTRAINT "FK_c6e648aeaab79e4213def02aba8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_roles" ADD CONSTRAINT "FK_a67d9923019611146f3527e6e3c" FOREIGN KEY ("guild_id") REFERENCES "guilds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_memberships" ADD CONSTRAINT "FK_fb83bb45d755767905a878005bc" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_memberships" ADD CONSTRAINT "FK_5c19b207cf13b2e4b0c2650e755" FOREIGN KEY ("guild_id") REFERENCES "guilds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_memberships" ADD CONSTRAINT "FK_7148edd5e72f5cc4ad92a666f9d" FOREIGN KEY ("role_id") REFERENCES "guild_roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_memberships" ADD CONSTRAINT "FK_b9882ea765c84502f9c1ceeff51" FOREIGN KEY ("invited_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_poll_options" ADD CONSTRAINT "FK_923fb6d5646e67d446e6bad3f52" FOREIGN KEY ("announcement_id") REFERENCES "guild_announcements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_announcements" ADD CONSTRAINT "FK_58c3839b03ffebaafb4e9d7903b" FOREIGN KEY ("guild_id") REFERENCES "guilds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_announcements" ADD CONSTRAINT "FK_6371108e17d759346021201a947" FOREIGN KEY ("author_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_announcements" ADD CONSTRAINT "FK_6fc2799ad3c7b5d18a86a064d89" FOREIGN KEY ("author_character_id") REFERENCES "characters"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_event_attendance" ADD CONSTRAINT "FK_27f15f88984603ff99a86e0faff" FOREIGN KEY ("event_id") REFERENCES "guild_internal_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_event_attendance" ADD CONSTRAINT "FK_3b7894d54762392b719f004483b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_event_attendance" ADD CONSTRAINT "FK_2cc96dce3af13fee705b2f07067" FOREIGN KEY ("character_id") REFERENCES "characters"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_internal_events" ADD CONSTRAINT "FK_5ff303ee25ac2829fe8fa3a2a6f" FOREIGN KEY ("guild_id") REFERENCES "guilds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_internal_events" ADD CONSTRAINT "FK_c3077615326168801291887c8d1" FOREIGN KEY ("creator_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_internal_events" ADD CONSTRAINT "FK_18526b51689d35043b96b4ece94" FOREIGN KEY ("creator_character_id") REFERENCES "characters"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guilds" ADD CONSTRAINT "FK_d1dd78882d0afcbbc38c502678a" FOREIGN KEY ("leader_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_media" ADD CONSTRAINT "FK_16a84aef47c794ac3d01f39830c" FOREIGN KEY ("event_id") REFERENCES "global_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_media" ADD CONSTRAINT "FK_d05b0201c6ee0b670e7ef3248ee" FOREIGN KEY ("uploader_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "global_events" ADD CONSTRAINT "FK_c6fcc664471b26f0aa4a4f0df32" FOREIGN KEY ("creator_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "global_events" ADD CONSTRAINT "FK_4396afc7710a3735481c774e602" FOREIGN KEY ("category_id") REFERENCES "event_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "global_event_attendance" ADD CONSTRAINT "FK_7a958a9f0543bb9d822ad11a6c4" FOREIGN KEY ("event_id") REFERENCES "global_events"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "global_event_attendance" ADD CONSTRAINT "FK_0c14a95e7ebcd3df144bb0fb288" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "global_event_attendance" ADD CONSTRAINT "FK_32e8e7a1daf1e40fbb773d43abc" FOREIGN KEY ("character_id") REFERENCES "characters"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a42daa89db36f5d49fa422c5c37" FOREIGN KEY ("active_character_id") REFERENCES "characters"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_votes" ADD CONSTRAINT "FK_23ab463e708b4c558125618fda0" FOREIGN KEY ("announcement_id") REFERENCES "guild_announcements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_votes" ADD CONSTRAINT "FK_7cf40a645ea7d56c34bf50e0b0c" FOREIGN KEY ("poll_option_id") REFERENCES "guild_poll_options"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_votes" ADD CONSTRAINT "FK_02486d2de1f609c0094a22c524b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_votes" ADD CONSTRAINT "FK_27996a9a36f2ec1403d2eccbd5d" FOREIGN KEY ("character_id") REFERENCES "characters"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_invites" ADD CONSTRAINT "FK_2d67aa5a10b6d9da6955265a71f" FOREIGN KEY ("guild_id") REFERENCES "guilds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_invites" ADD CONSTRAINT "FK_64c4f2d7d3aaf5d711d14975599" FOREIGN KEY ("sender_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_invites" ADD CONSTRAINT "FK_325bbf553def4fb4cc5b58eec44" FOREIGN KEY ("target_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "guild_invites" ADD CONSTRAINT "FK_3025898b9191b091452949c0fac" FOREIGN KEY ("handled_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_attachments" ADD CONSTRAINT "FK_36f9810618284e1e269eeedaefd" FOREIGN KEY ("message_id") REFERENCES "chat_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message_reads" ADD CONSTRAINT "FK_dd6a3591a743252a7c728646348" FOREIGN KEY ("message_id") REFERENCES "chat_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message_reads" ADD CONSTRAINT "FK_18f427cc65039a310351dd87546" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_31c45c915d0e437e80a63b17749" FOREIGN KEY ("channel_id") REFERENCES "chat_channels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_73245e057f063d01b5510f6d46f" FOREIGN KEY ("sender_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_71193961ce87a8db0f566e50013" FOREIGN KEY ("sender_character_id") REFERENCES "characters"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_46d19cf514d5c46a1f15598cf1c" FOREIGN KEY ("reply_to_id") REFERENCES "chat_messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_channels" ADD CONSTRAINT "FK_66c9b5f4ac787a7c4f0846f652f" FOREIGN KEY ("guild_id") REFERENCES "guilds"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participants" ADD CONSTRAINT "FK_3da3f5e9f8f91f6ac6b0c2e31a6" FOREIGN KEY ("channel_id") REFERENCES "chat_channels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participants" ADD CONSTRAINT "FK_b4129b3e21906ca57b503a1d834" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_participants" ADD CONSTRAINT "FK_6452d1cad8f92b30797c1aaa9de" FOREIGN KEY ("character_id") REFERENCES "characters"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c"`);
        await queryRunner.query(`ALTER TABLE "chat_participants" DROP CONSTRAINT "FK_6452d1cad8f92b30797c1aaa9de"`);
        await queryRunner.query(`ALTER TABLE "chat_participants" DROP CONSTRAINT "FK_b4129b3e21906ca57b503a1d834"`);
        await queryRunner.query(`ALTER TABLE "chat_participants" DROP CONSTRAINT "FK_3da3f5e9f8f91f6ac6b0c2e31a6"`);
        await queryRunner.query(`ALTER TABLE "chat_channels" DROP CONSTRAINT "FK_66c9b5f4ac787a7c4f0846f652f"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_46d19cf514d5c46a1f15598cf1c"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_71193961ce87a8db0f566e50013"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_73245e057f063d01b5510f6d46f"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_31c45c915d0e437e80a63b17749"`);
        await queryRunner.query(`ALTER TABLE "chat_message_reads" DROP CONSTRAINT "FK_18f427cc65039a310351dd87546"`);
        await queryRunner.query(`ALTER TABLE "chat_message_reads" DROP CONSTRAINT "FK_dd6a3591a743252a7c728646348"`);
        await queryRunner.query(`ALTER TABLE "chat_attachments" DROP CONSTRAINT "FK_36f9810618284e1e269eeedaefd"`);
        await queryRunner.query(`ALTER TABLE "guild_invites" DROP CONSTRAINT "FK_3025898b9191b091452949c0fac"`);
        await queryRunner.query(`ALTER TABLE "guild_invites" DROP CONSTRAINT "FK_325bbf553def4fb4cc5b58eec44"`);
        await queryRunner.query(`ALTER TABLE "guild_invites" DROP CONSTRAINT "FK_64c4f2d7d3aaf5d711d14975599"`);
        await queryRunner.query(`ALTER TABLE "guild_invites" DROP CONSTRAINT "FK_2d67aa5a10b6d9da6955265a71f"`);
        await queryRunner.query(`ALTER TABLE "guild_votes" DROP CONSTRAINT "FK_27996a9a36f2ec1403d2eccbd5d"`);
        await queryRunner.query(`ALTER TABLE "guild_votes" DROP CONSTRAINT "FK_02486d2de1f609c0094a22c524b"`);
        await queryRunner.query(`ALTER TABLE "guild_votes" DROP CONSTRAINT "FK_7cf40a645ea7d56c34bf50e0b0c"`);
        await queryRunner.query(`ALTER TABLE "guild_votes" DROP CONSTRAINT "FK_23ab463e708b4c558125618fda0"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a42daa89db36f5d49fa422c5c37"`);
        await queryRunner.query(`ALTER TABLE "global_event_attendance" DROP CONSTRAINT "FK_32e8e7a1daf1e40fbb773d43abc"`);
        await queryRunner.query(`ALTER TABLE "global_event_attendance" DROP CONSTRAINT "FK_0c14a95e7ebcd3df144bb0fb288"`);
        await queryRunner.query(`ALTER TABLE "global_event_attendance" DROP CONSTRAINT "FK_7a958a9f0543bb9d822ad11a6c4"`);
        await queryRunner.query(`ALTER TABLE "global_events" DROP CONSTRAINT "FK_4396afc7710a3735481c774e602"`);
        await queryRunner.query(`ALTER TABLE "global_events" DROP CONSTRAINT "FK_c6fcc664471b26f0aa4a4f0df32"`);
        await queryRunner.query(`ALTER TABLE "event_media" DROP CONSTRAINT "FK_d05b0201c6ee0b670e7ef3248ee"`);
        await queryRunner.query(`ALTER TABLE "event_media" DROP CONSTRAINT "FK_16a84aef47c794ac3d01f39830c"`);
        await queryRunner.query(`ALTER TABLE "guilds" DROP CONSTRAINT "FK_d1dd78882d0afcbbc38c502678a"`);
        await queryRunner.query(`ALTER TABLE "guild_internal_events" DROP CONSTRAINT "FK_18526b51689d35043b96b4ece94"`);
        await queryRunner.query(`ALTER TABLE "guild_internal_events" DROP CONSTRAINT "FK_c3077615326168801291887c8d1"`);
        await queryRunner.query(`ALTER TABLE "guild_internal_events" DROP CONSTRAINT "FK_5ff303ee25ac2829fe8fa3a2a6f"`);
        await queryRunner.query(`ALTER TABLE "guild_event_attendance" DROP CONSTRAINT "FK_2cc96dce3af13fee705b2f07067"`);
        await queryRunner.query(`ALTER TABLE "guild_event_attendance" DROP CONSTRAINT "FK_3b7894d54762392b719f004483b"`);
        await queryRunner.query(`ALTER TABLE "guild_event_attendance" DROP CONSTRAINT "FK_27f15f88984603ff99a86e0faff"`);
        await queryRunner.query(`ALTER TABLE "guild_announcements" DROP CONSTRAINT "FK_6fc2799ad3c7b5d18a86a064d89"`);
        await queryRunner.query(`ALTER TABLE "guild_announcements" DROP CONSTRAINT "FK_6371108e17d759346021201a947"`);
        await queryRunner.query(`ALTER TABLE "guild_announcements" DROP CONSTRAINT "FK_58c3839b03ffebaafb4e9d7903b"`);
        await queryRunner.query(`ALTER TABLE "guild_poll_options" DROP CONSTRAINT "FK_923fb6d5646e67d446e6bad3f52"`);
        await queryRunner.query(`ALTER TABLE "guild_memberships" DROP CONSTRAINT "FK_b9882ea765c84502f9c1ceeff51"`);
        await queryRunner.query(`ALTER TABLE "guild_memberships" DROP CONSTRAINT "FK_7148edd5e72f5cc4ad92a666f9d"`);
        await queryRunner.query(`ALTER TABLE "guild_memberships" DROP CONSTRAINT "FK_5c19b207cf13b2e4b0c2650e755"`);
        await queryRunner.query(`ALTER TABLE "guild_memberships" DROP CONSTRAINT "FK_fb83bb45d755767905a878005bc"`);
        await queryRunner.query(`ALTER TABLE "guild_roles" DROP CONSTRAINT "FK_a67d9923019611146f3527e6e3c"`);
        await queryRunner.query(`ALTER TABLE "characters" DROP CONSTRAINT "FK_c6e648aeaab79e4213def02aba8"`);
        await queryRunner.query(`ALTER TABLE "character_properties" DROP CONSTRAINT "FK_7558da41805c32a4570072842bd"`);
        await queryRunner.query(`DROP INDEX "public"."ux_prt_token_hash"`);
        await queryRunner.query(`DROP INDEX "public"."ix_prt_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_prt_expires"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."ux_cp_user_channel"`);
        await queryRunner.query(`DROP INDEX "public"."ix_cp_channel_active"`);
        await queryRunner.query(`DROP TABLE "chat_participants"`);
        await queryRunner.query(`DROP TYPE "public"."chat_participants_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."chat_participants_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_cc_guild"`);
        await queryRunner.query(`DROP INDEX "public"."ix_cc_lastmsg"`);
        await queryRunner.query(`DROP INDEX "public"."ux_cc_direct_hash"`);
        await queryRunner.query(`DROP TABLE "chat_channels"`);
        await queryRunner.query(`DROP TYPE "public"."chat_channels_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_cm_channel_sent"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_cmr_user"`);
        await queryRunner.query(`DROP INDEX "public"."ix_cmr_message"`);
        await queryRunner.query(`DROP TABLE "chat_message_reads"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ca_message"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ca_mime"`);
        await queryRunner.query(`DROP TABLE "chat_attachments"`);
        await queryRunner.query(`DROP INDEX "public"."ix_gi_guild_status"`);
        await queryRunner.query(`DROP INDEX "public"."ux_gi_token_hash"`);
        await queryRunner.query(`DROP TABLE "guild_invites"`);
        await queryRunner.query(`DROP TYPE "public"."guild_invites_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."guild_invites_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ux_gv_one_vote_per_option"`);
        await queryRunner.query(`DROP TABLE "guild_votes"`);
        await queryRunner.query(`DROP INDEX "public"."ux_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."ux_users_username"`);
        await queryRunner.query(`DROP INDEX "public"."ix_users_active_char"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."ix_gea_event_status"`);
        await queryRunner.query(`DROP INDEX "public"."ix_gea_user"`);
        await queryRunner.query(`DROP TABLE "global_event_attendance"`);
        await queryRunner.query(`DROP TYPE "public"."global_event_attendance_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ge_cat_start"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ge_status_date"`);
        await queryRunner.query(`DROP TABLE "global_events"`);
        await queryRunner.query(`DROP TYPE "public"."global_events_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_em_event_pos"`);
        await queryRunner.query(`DROP INDEX "public"."ix_em_mime"`);
        await queryRunner.query(`DROP TABLE "event_media"`);
        await queryRunner.query(`DROP INDEX "public"."ux_ec_name"`);
        await queryRunner.query(`DROP INDEX "public"."ux_ec_slug"`);
        await queryRunner.query(`DROP INDEX "public"."ux_ec_pos"`);
        await queryRunner.query(`DROP TABLE "event_categories"`);
        await queryRunner.query(`DROP INDEX "public"."ux_guild_name"`);
        await queryRunner.query(`DROP INDEX "public"."ux_guild_slug"`);
        await queryRunner.query(`DROP INDEX "public"."ix_guild_leader"`);
        await queryRunner.query(`DROP TABLE "guilds"`);
        await queryRunner.query(`DROP TYPE "public"."guilds_access_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."guilds_privacy_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_gie_guild_start"`);
        await queryRunner.query(`DROP INDEX "public"."ix_gie_status"`);
        await queryRunner.query(`DROP TABLE "guild_internal_events"`);
        await queryRunner.query(`DROP TYPE "public"."guild_internal_events_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ux_gatt_user_event"`);
        await queryRunner.query(`DROP INDEX "public"."ix_gatt_event_confirmed"`);
        await queryRunner.query(`DROP TABLE "guild_event_attendance"`);
        await queryRunner.query(`DROP TYPE "public"."guild_event_attendance_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ga_guild_created"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ga_type"`);
        await queryRunner.query(`DROP TABLE "guild_announcements"`);
        await queryRunner.query(`DROP TYPE "public"."guild_announcements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_gpo_announcement"`);
        await queryRunner.query(`DROP TABLE "guild_poll_options"`);
        await queryRunner.query(`DROP INDEX "public"."ux_gm_user_guild"`);
        await queryRunner.query(`DROP INDEX "public"."ix_gm_status"`);
        await queryRunner.query(`DROP INDEX "public"."ix_gm_guild_active"`);
        await queryRunner.query(`DROP TABLE "guild_memberships"`);
        await queryRunner.query(`DROP TYPE "public"."guild_memberships_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ux_role_name"`);
        await queryRunner.query(`DROP INDEX "public"."ux_role_position"`);
        await queryRunner.query(`DROP INDEX "public"."ux_role_one_leader"`);
        await queryRunner.query(`DROP TABLE "guild_roles"`);
        await queryRunner.query(`DROP INDEX "public"."ux_char_user_name"`);
        await queryRunner.query(`DROP INDEX "public"."ux_char_slug"`);
        await queryRunner.query(`DROP TABLE "characters"`);
        await queryRunner.query(`DROP INDEX "public"."ux_prop_char_key"`);
        await queryRunner.query(`DROP TABLE "character_properties"`);
    }

}
